# Site settings
title: IDInteraction
email: caroline.jay@manchester.ac.uk
description: >
  Capturing Indicative Usage Models in Software for Implicit Device Interaction
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://idinteraction.cs.manchester.ac.uk" # the base hostname & protocol for your site
github_username: "IDInteraction"

# Build settings
markdown: kramdown
